brew "antigen"
brew "circleci"
brew "git"
brew "hub"
brew "jq"
brew "mas"
brew "netlify-cli"
brew "yadm"
brew "yarn"
brew "zsh"

cask "1password"
cask "elgato-stream-deck"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "logitech-camera-settings"
cask "logitech-options"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "visual-studio-code"
cask "zoom"

mas "Magnet", id: 441258766
